# This file was generated by GoReleaser. DO NOT EDIT.
cask "testground" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "2c8a9afdc8fe40a6aeef397f03233fe7179dfded17c3f7b2268f94785bcdd067"
      url "https://github.com/heyrmi/testground/releases/download/v0.8.0/testground_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
    on_arm do
      sha256 "62cadaffe3f24a13ffa156c908506e45a1d1b2853e2a636f4e02c6463b983250"
      url "https://github.com/heyrmi/testground/releases/download/v0.8.0/testground_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
  end

  on_linux do
    on_intel do
      sha256 "0985e52fef7230c54f48c0bb5d6f7cf051f7d17c4060ae2c66be92bc1e28cf43"
      url "https://github.com/heyrmi/testground/releases/download/v0.8.0/testground_#{version}_linux_amd64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
    on_arm do
      sha256 "186bb88789adf9af8285ed6969048cef42f0f138a91a0649aa8e641de89bb6cf"
      url "https://github.com/heyrmi/testground/releases/download/v0.8.0/testground_#{version}_linux_arm64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
  end

  name "testground"
  desc "A self-contained playground of browser-automation challenges for QA engineers"
  homepage "https://github.com/heyrmi/testground"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "playground"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/playground"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Start the playground with:

      playground serve

    It binds 127.0.0.1:7373, and a second origin on 127.0.0.1:7374 that the
    cross-origin frame challenges embed. Nothing is fetched over the network.
  EOS
end
