# This file was generated by GoReleaser. DO NOT EDIT.
cask "testground" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "b678a0ecbc4b8c764f394a8e2909d4982f60446af86cf6f8a1c1984335a10504"
      url "https://github.com/heyrmi/testground/releases/download/v#{version}/testground_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
    on_arm do
      sha256 "5f50f97b743f3c066e304921e58ef7eb037369149704886ac2aa1dfb1147d4b8"
      url "https://github.com/heyrmi/testground/releases/download/v#{version}/testground_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
  end

  on_linux do
    on_intel do
      sha256 "090644838aaf58928c6c7c69cef0664ba9efc7a2d4d635ec497e1e8223163cd3"
      url "https://github.com/heyrmi/testground/releases/download/v#{version}/testground_#{version}_linux_amd64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
    on_arm do
      sha256 "3af52780fbfa116908b326525c3b4ffa570dc964e2f294d856b6c9fa2f18b365"
      url "https://github.com/heyrmi/testground/releases/download/v#{version}/testground_#{version}_linux_arm64.tar.gz",
        verified: "github.com/heyrmi/testground"
    end
  end

  name "testground"
  desc "A self-contained playground of browser-automation challenges for QA engineers"
  homepage "https://github.com/heyrmi/testground"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "playground"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/playground"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Start the playground with:

      playground serve

    It binds 127.0.0.1:7373, and a second origin on 127.0.0.1:7374 that the
    cross-origin frame challenges embed. Nothing is fetched over the network.
  EOS
end
